#!/usr/bin/env bash
# test-story-4.4-integration.sh — ATDD Integration (compile + fresh-user + regression) Tests for Story 4.4
# TDD Phase: GREEN-GATE — Story 4.4 is DOCS-ONLY (verify/checklist.md + verify/baseline/ + README rewrite). It touches
#             NO cls/def/main.tex/data, so the COMPILE PATH IS UNAFFECTED. Therefore the integration layer has NO RED
#             drivers (the RED is all unit/doc-level: artifacts absent, README still ZZU — see test-story-4.4-unit.sh).
#             The 4 integration tests are GREEN GATES/GUARDS that prove "docs-only did not regress the compile":
#               I01 (gate) default compile rc0/errors0/warnings≤baseline+3/pages≥40,
#               I02 (AC-10) default .log self-check structurally identical to 7e0d103 (markers + 8 dims + 4.2 sections
#                   + debug section ABSENT on default — 4.4 consumer, no cls edit),
#               I03 (TC-E4-31) fresh-user clean-compile: rm intermediates + latexmk -xelatex main exit 0 (NO make
#                   dependency — 4.3 Windows-no-make precedent; README documents latexmk as the primary command),
#               I04 (guard) 4.3 Makefile calibrate + debug-check RECIPES intact (4.4 documents these tools, does not
#                   change them).
#
# Usage: bash tests/test-story-4.4-integration.sh [--run]
#   --run    Remove SKIP marker (for green-phase verification)
#
# Priority: P0 (I01 compile gate + I02 self-check intact + I03 fresh-user compile — the no-regression pillars) /
#           P1 (I04 4.3-tools recipe intact)
# Linked ACs: AC-8 (fresh-user compiles via README only), AC-10 (no regression — self-check byte-identical, 4.3 tools)
# Linked Risk: R-28 (README fresh-user compile — I03), R-27/R-25 (checklist — unit-level, not integration)
# TC coverage: TC-E4-31 (I03 fresh-user compile)
#
# FRESH-USER PATTERN: simulate a clean checkout by removing the build intermediates (main.aux/bbl/fdb_latexmk/fls/
#   toc/out/lof/lot/bcf/blg/xdv), then compile via `latexmk -xelatex main` (the README's documented primary command —
#   NOT `make`, per the 4.3 Windows-no-make precedent). Assert exit 0 + main.pdf exists + page count sane. The
#   intermediates are regenerated by latexmk; no source is touched. SUT (main.tex/cls/def/data) UNTOUCHED.
#
# Truth source: architecture.md §524–568 (project structure + verify/ boundary) + §534/§542–552 (README); test-design-
#   epic-4.md R-28 (README fresh-user compile) + TC-E4-31; htuthesis.def geometry (baseline self-check values); the
#   \htucheck 4.2 output contract (markers + 8 dim lines + font block + coverage map + assertion audit — the 23+ ATDD
#   consumers incl. the 4.4 checklist depend on these; 4.4 must not change them, AC-10). spec PRIORITY (CLAUDE.md).
#
# Line refs verified vs HEAD 7e0d103: main.tex compiles clean (1 xeCJK warning, ~52 pages per Story 4.3 close-out);
#   \htucheck = cls:1067–1165 (4.2 + 4.3 debug section); Makefile has calibrate (Makefile:62) + debug-check (Makefile:72).

set -uo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$DIR"

# --- TDD Red Phase Control ---
SKIP="${ATDD_SKIP:-1}"

if [[ "${1:-}" == "--run" ]]; then
  SKIP=0
fi

PASS=0
FAIL=0
SKIP_COUNT=0

green()  { printf "\033[32m  [PASS] %s\033[0m\n" "$1"; }
red()    { printf "\033[31m  [FAIL] %s\033[0m\n" "$1"; }
yellow() { printf "\033[33m  [SKIP] %s\033[0m\n" "$1"; }

run_test() {
  local priority="$1"
  local test_id="$2"
  local description="$3"

  if [[ "$SKIP" == "1" ]]; then
    yellow "[$priority] $test_id: $description"
    ((SKIP_COUNT++))
    return 0
  fi

  shift 3
  "$@"
  if [[ $? -eq 0 ]]; then
    green "[$priority] $test_id: $description"
    ((PASS++))
  else
    red "[$priority] $test_id: $description"
    ((FAIL++))
  fi
}

# Makefile actual flags (Makefile:3) — used by all compile paths
LATEXMK="latexmk -xelatex -file-line-error -halt-on-error -interaction=nonstopmode"
WARN_THRESHOLD=4   # baseline (1 xeCJK) + 3 (NFR-1 budget); 4.4 docs-only must not add warnings

# ==========================================
# P0 — gate: default compile rc0/errors0/warnings≤baseline+3/pages≥40
# ==========================================
echo "=== P0: default compile gate (rc0, errors0, warnings≤$WARN_THRESHOLD, pages≥40) ==="

# ATDD-4.4-I01: a default `latexmk main` compile must succeed with rc=0, zero `^!`/LaTeX errors, warnings ≤ baseline+3,
#   and a sane page count (≥40). This is the GREEN gate — 4.4 is docs-only, so the compile must be unaffected. Pre-impl
#   (7e0d103): compiles clean (1 xeCJK warning, ~52pp). RED post-impl would mean the README rewrite or verify/ creation
#   accidentally touched a source file (scope violation).
test_default_compile_gate() {
  $LATEXMK main >/dev/null 2>&1
  local rc=$?
  [[ $rc -eq 0 ]] || { echo "  (compile rc=$rc — RED)"; return 1; }
  [[ -f main.pdf ]] || { echo "  (main.pdf not produced — RED)"; return 1; }
  [[ -f main.log ]] || { echo "  (main.log not produced — RED)"; return 1; }
  local errors warns pages
  errors=$(grep -cE '^\!|^! ' main.log 2>/dev/null || true)
  # LaTeX Error: lines (file-line-error form) also count
  local lerr
  lerr=$(grep -cE 'LaTeX Error:|^! ' main.log 2>/dev/null || true)
  # warning count via the 4.3 pattern (Package X Warning: / LaTeX Warning: — colon-anchored so it does NOT trip on
  # the \htucheck \typeout watch-list text, which prints the NFR-5 signatures as plain log lines without a `Warning:`
  # colon). Baseline = 1 (xeCJK benign, 4.3 close-out). Broad `grep 'Warning'` would over-count (watch-list typeouts).
  warns=$(grep -cE '^Package .* Warning:|^LaTeX Warning:|Warning:' main.log 2>/dev/null | tr -d '[:space:]')
  [[ -z "$warns" ]] && warns=0
  # page count via the self-check 'total pages = ' line (cls:1077)
  pages=$(grep -oE 'total pages = [0-9]+' main.log | grep -oE '[0-9]+' || echo 0)
  echo "  rc=$rc errors=$errors latex-errors=$lerr warnings=$warns pages=$pages"
  [[ "$errors" -eq 0 && "$lerr" -eq 0 ]] || { echo "  (errors present — RED)"; return 1; }
  [[ "$warns" -le "$WARN_THRESHOLD" ]] || { echo "  (warnings $warns > $WARN_THRESHOLD — RED, NFR-1)"; return 1; }
  [[ "$pages" -ge 40 ]] || { echo "  (pages $pages < 40 — RED, anomaly)"; return 1; }
  echo "  (default compile GREEN — rc0/errors0/warns≤$WARN_THRESHOLD/pages≥40)"
  return 0
}
run_test "P0" "ATDD-4.4-I01" "default compile gate rc0/errors0/warns≤$WARN_THRESHOLD/pages≥40 (AC-10; GREEN gate pre+post — docs-only)" test_default_compile_gate

# ==========================================
# P0 — AC-10: default .log self-check structurally identical to 7e0d103 (4.4 consumer, no cls edit)
# ==========================================
echo "=== P0: default .log self-check intact (markers + 8 dims + 4.2 sections + no debug section) (AC-10) ==="

# ATDD-4.4-I02: the default-compile main.log must contain the FULL \htucheck self-check block — markers + 8 name=value
#   dim lines + font block + coverage map + assertion audit — AND must NOT contain the `--- debug diagnostics ---`
#   section (that is \ifhtu@debug-gated, 4.3; only on [doctor,debug]). 4.4 is a CONSUMER of these output strings (the
#   checklist references them); it MUST NOT change them. GREEN gate pre+post. RED = 4.4 edited the cls / debug leaked.
test_selfcheck_intact() {
  [[ -f main.log ]] || $LATEXMK main >/dev/null 2>&1
  [[ -f main.log ]] || { echo "  (no main.log — RED)"; return 1; }
  # python reads main.log (Windows grep -qiF crashes core-dump on this file's content — harness bug, not a test
  #   contract issue; python is the robust read path used throughout the project's ATDDs).
  python - <<'PY'
import sys
src = open("main.log", encoding="utf-8", errors="replace").read()
checks = {
    "start-marker":  "=== HTU Layout Self-Check ===" in src,
    "end-marker":    "=== End Self-Check ===" in src,
    "textheight dim": "textheight = " in src,
    "textwidth dim":  "textwidth = " in src,
    "baselineskip dim": "baselineskip = " in src,
    "headheight dim": "headheight = " in src,
    "evensidemargin dim": "evensidemargin = " in src,
    "oddsidemargin dim":  "oddsidemargin = " in src,
    "total pages dim":    "total pages = " in src,
    "page counter dim":   "page counter = " in src,
    "font-check block":   "font check" in src,
    "coverage map":       "silent-failure coverage map" in src,
    "assertion audit":    "assertion audit" in src,
}
missing = [n for n, ok in checks.items() if not ok]
# debug section MUST be ABSENT on the default compile (4.3 \ifhtu@debug gating intact; 4.4 must not add debug noise)
debug_leak = "--- debug diagnostics ---" in src
# no htuthesis ERROR (font-missing \PackageError would have halted; default compile is clean)
has_error = "htuthesis ERROR" in src
print("  checks present: %d/%d" % (len([1 for ok in checks.values() if ok]), len(checks)))
if missing:
    print("  RED: missing %s" % missing)
if debug_leak:
    print("  RED: debug section present on DEFAULT compile (4.3 \\ifhtu@debug gating regressed)")
if has_error:
    print("  RED: htuthesis ERROR in log (font/self-check error)")
sys.exit(0 if (not missing and not debug_leak and not has_error) else 1)
PY
}
run_test "P0" "ATDD-4.4-I02" "default .log self-check structurally identical to 7e0d103 (AC-10; GREEN gate — 4.4 consumer, no cls edit)" test_selfcheck_intact

# ==========================================
# P0 — TC-E4-31: fresh-user clean-compile via latexmk (no make dependency)
# ==========================================
echo "=== P0: fresh-user clean-compile via latexmk (AC-8, TC-E4-31, R-28) ==="

# ATDD-4.4-I03: simulate a clean checkout — remove the build intermediates, then compile via the README's documented
#   primary command `latexmk -xelatex main` (NOT make — 4.3 Windows-no-make precedent; README quick-start lists latexmk
#   as primary). Assert rc=0 + main.pdf exists + page count sane. This proves the README's documented command works
#   from a clean state (AC-8 fresh-user). GREEN gate (main.tex compiles regardless of README content) — the RED
#   aspect of AC-8 (README correctness) is enforced at unit-level (unit-04/05/06).
test_fresh_user_compile() {
  # remove intermediates (simulate clean checkout); latexmk regenerates them. SUT (source) UNTOUCHED.
  rm -f main.aux main.bbl main.fdb_latexmk main.fls main.toc main.out main.lof main.lot main.run.xml main.bcf main.blg main.xdv 2>/dev/null || true
  $LATEXMK main >/dev/null 2>&1
  local rc=$?
  [[ $rc -eq 0 ]] || { echo "  (fresh-user compile rc=$rc — RED)"; return 1; }
  [[ -f main.pdf ]] || { echo "  (main.pdf not produced after clean-compile — RED)"; return 1; }
  local pages
  pages=$(grep -oE 'total pages = [0-9]+' main.log | grep -oE '[0-9]+' || echo 0)
  echo "  fresh-user latexmk rc=$rc pages=$pages"
  [[ "$pages" -ge 40 ]] || { echo "  (pages $pages < 40 — RED)"; return 1; }
  echo "  (fresh-user clean-compile via latexmk GREEN — rc0/main.pdf/pages≥40)"
  return 0
}
run_test "P0" "ATDD-4.4-I03" "fresh-user clean-compile via latexmk (AC-8, TC-E4-31; GREEN gate — no make dependency, R-28)" test_fresh_user_compile

# ==========================================
# P1 — guard: 4.3 Makefile calibrate + debug-check RECIPES intact (4.4 documents, not changes)
# ==========================================
echo "=== P1: 4.3 Makefile calibrate + debug-check recipes intact (AC-10, 4.3 tools) ==="

# ATDD-4.4-I04: the Makefile `calibrate` + `debug-check` targets (Story 4.3) must remain — 4.4's checklist DOCUMENTS
#   these tools (as auto-check references), it does not change them. GREEN guard pre+post. Checks the RECIPE authoring
#   (not `make` execution — `make` may be absent on the Windows dev env, 4.3 precedent; the recipe correctness is what
#   4.4 must preserve). RED = 4.4 removed/broke a 4.3 target.
test_makefile_43_recipes_intact() {
  [[ -f Makefile ]] || { echo "  (no Makefile — RED)"; return 1; }
  grep -qE '^[[:space:]]*calibrate[[:space:]]*:' Makefile || { echo "  (calibrate target missing — RED, 4.3 regression)"; return 1; }
  grep -qE '^[[:space:]]*debug-check[[:space:]]*:' Makefile || { echo "  (debug-check target missing — RED, 4.3 regression)"; return 1; }
  # calibrate recipe references tools/calibrate.tex
  grep -qE 'tools/calibrate' Makefile || { echo "  (calibrate recipe lost its tools/calibrate.tex ref — RED)"; return 1; }
  # debug-check recipe has the 6-signature grep (NFR-5 watch-list)
  grep -qE 'Overfull|geometry Warning|headheight|Citation|Token not allowed|caption Warning' Makefile || { echo "  (debug-check recipe lost NFR-5 signatures — RED)"; return 1; }
  # neither wired into default all (4.3 opt-in contract)
  if grep -Eq '^all[[:space:]]*:.*(calibrate|debug-check)' Makefile; then
    echo "  (calibrate/debug-check wired into default 'all' — RED, 4.3 opt-in contract broken)"; return 1
  fi
  echo "  (4.3 calibrate + debug-check recipes intact + opt-in — GREEN, 4.4 documents not changes)"
  return 0
}
run_test "P1" "ATDD-4.4-I04" "4.3 Makefile calibrate + debug-check recipes intact + opt-in (AC-10; GREEN guard — 4.4 documents these tools)" test_makefile_43_recipes_intact

echo ""
echo "=============================================="
echo "Summary: PASS=$PASS FAIL=$FAIL SKIP=$SKIP_COUNT"
echo "=============================================="
if [[ "$SKIP" == "1" ]]; then
  echo ""
  echo "   TDD GREEN-GATE phase — 4.4 is DOCS-ONLY. Integration has NO RED drivers (the RED is unit/doc-level:"
  echo "   artifacts absent + README ZZU — see test-story-4.4-unit.sh). These 4 GREEN gates prove 'docs-only did not"
  echo "   regress the compile'. Activate with --run or ATDD_SKIP=0."
  echo "   GREEN gates (PASS pre+post 7e0d103):"
  echo "      I01 default compile rc0/errors0/warns≤$WARN_THRESHOLD/pages≥40 (AC-10)"
  echo "      I02 default .log self-check intact (markers + 8 dims + 4.2 sections + no debug) (AC-10)"
  echo "      I03 fresh-user clean-compile via latexmk (AC-8, TC-E4-31, R-28 — NO make dependency)"
  echo "      I04 4.3 calibrate + debug-check Makefile recipes intact + opt-in (AC-10)"
  echo ""
  echo "   The compile path is UNAFFECTED by 4.4 (docs-only). I01/I02 are the AC-10 no-regression linchpins."
  echo "   I03 proves the README's documented command works from a clean state (R-28 fresh-user)."
  echo "   I04 proves 4.4 documented the 4.3 tools without changing them."
  echo "   SUT (main.tex/cls/def/data) UNTOUCHED — only build intermediates are regenerated (Epic 1 retro)."
fi

if [[ "$SKIP" != "1" ]] && [[ "$FAIL" -gt 0 ]]; then
  exit 1
fi
exit 0
